[package]
name = "komorebi-ui"
version = "1.0.0"
description = "Komorebi UI Background"
authors = ["eythaann"]
license = "MIT"
repository = "https://github.com/eythaann/komorebi-ui.git"
default-run = "komorebi-ui"
edition = "2021"
rust-version = "1.60"
build = "scripts/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "komorebi-ui"
path = "src/background/main.rs"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta", features = ["tray-icon", "image-png"] }
tauri-plugin-fs = "2.0.0-beta.2"
tauri-plugin-dialog = "2.0.0-beta.2"
tauri-plugin-autostart = "2.0.0-beta.2"
tauri-plugin-single-instance = "2.0.0-beta.2"
tauri-plugin-shell = "2.0.0-beta.2"
tauri-plugin-process = "2.0.0-beta.2"
tauri-plugin-log = { version = "2.0.0-beta.2", features = ["colored"] }
color-eyre = "0.6.2"
lazy_static = "1.4.0"
parking_lot = "0.12.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-cli = "2.0.0-beta.2"
