cargo-features = ["profile-rustflags"]

[package]
name = "seelen-ui"
version = "1.0.0"
description = "Seelen UI Background"
authors = ["eythaann"]
license = "Polyform Strict License"
repository = "https://github.com/eythaann/seelen-ui.git"
default-run = "seelen-ui"
edition = "2021"
rust-version = "1.60"
build = "scripts/build.rs"

[[bin]]
name = "seelen-ui"
path = "src/background/main.rs"

[profile.dev]
incremental = true
rustflags = ["-Z", "threads=8"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
winvd = { git = "https://github.com/eythaann/virtualdesktopaccessor.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
tauri = { version = "2.0.0-beta", features = [
    "protocol-asset",
    "tray-icon",
    "image-png",
] }
tauri-plugin-fs = "2.0.0-beta.2"
tauri-plugin-dialog = "2.0.0-beta.2"
tauri-plugin-autostart = "2.0.0-beta.2"
tauri-plugin-shell = "2.0.0-beta.2"
tauri-plugin-process = "2.0.0-beta.2"
tauri-plugin-log = "2.0.0-beta.2"
tauri-plugin-updater = "2.0.0-beta.2"
color-eyre = "0.6.2"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
log = "0.4"
uuid = "1.8.0"
image = "0.25.0"
win-screenshot = "4.0.8"
widestring = "1.0.2"
itertools = "0.12.1"
clap = { version = "4.5.4", features = ["derive", "string"] }
os_info = "3.8.2"
winreg = "0.52.0"
crossbeam-channel = "0.5.12"
regex = "1.10.4"
getset = "0.1.2"
phf = "0.11.2"
sysinfo = "0.30.12"
battery = "0.7.8"

[dependencies.windows]
version = "=0.56.0"
features = [
    "Win32_Foundation",
    "ApplicationModel",
    "Foundation_Collections",
    "Management_Deployment",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_Accessibility",
    "Win32_Graphics_Dwm",
    "Win32_System_Com",
    "Win32_System_Registry",               # required for system tray icon module
    "Win32_Security",                      # required for power management (shutdown, reboot)
    "Win32_System_Threading",
    "Win32_System_StationsAndDesktops",
    "Win32_System_RemoteDesktop",
    "Win32_System_ProcessStatus",
    "Win32_System_Power",                  # required for power management (battery - AC)
    "Win32_System_Shutdown",               # required for power management (shutdown)
    "Win32_Storage_EnhancedStorage",
    "Win32_Media_Audio_Endpoints",         # required for audio module
    "Win32_Media_DeviceManager",           # required for audio module
    "Media",                               # required for audio module
    "Media_Control",                       # required for audio module
    "Storage_Streams",                     # required for audio module
    "Win32_Devices_Display",               # required for display (brightness, etc)
    "UI_Core",
    "Win32_NetworkManagement_IpHelper",    # required for network manager
    "Win32_NetworkManagement_Ndis",        # required for network manager
    "Win32_Networking_WinSock",            # required for network manager
    "Win32_Networking_NetworkListManager", # required for network manager // events
    "Win32_NetworkManagement_WiFi",        # required for network manager // wifi
]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
custom-protocol = ["tauri/custom-protocol"]
devtools = ["tauri/devtools"]
trace_lock = []
