info:
  displayName: Default
  author: eythaann,
  description: Default toolbar layout good for many devices.
left:
  - type: text
    template: concat("@", env.USERNAME)
    onClick: open -> env.USERPROFILE
    tooltip: '"Open user folder"'

  - type: text
    template: '"|"'

  - type: text
    template: window.name

  - type: text
    template: >
      window.title ? "-" : ""

  - type: text
    template: window.title

center:
  - type: date
    each: minute
    format: ddd D MMM, hh:mm A
    template: date

right:
  - type: tray
    template: icon.BsThreeDots
    tooltip: '"Open system tray"'

  - type: generic
    template: icon.TbBluetoothConnected
    onClick: open -> "ms-settings:bluetooth"
    tooltip: '"Bluetooth"'

  - type: network
    onClick: open -> "ms-settings:network"
    tooltip: >-
      online ? "Internet access" : "No internet access"
    template: >-
      online
      ? (
        unequal(usingInterface, null) and equalText(usingInterface.type, "IEEE80211")
          ? "[ICON:FaWifi:14]"
          : icon.TbWorld
      )
      : icon.TbWorldCancel

  - type: generic
    template: icon.IoVolumeHighOutline
    onClick: open -> "ms-settings:sound"
    tooltip: '"Sound"'

  - type: power
    tooltip: >-
      concat(string(battery.percentage), "% remaining", battery.smartCharging ? " - Smart Charge" : "")
    template: >-
      concat(
        string(equalText(battery.state, "charging") ? "[ICON:MdOutlineElectricBolt:12] " : ""),
        string(battery.smartCharging ? "[ICON:FaHeart:12] " : ""),
        string(
          battery.percentage > 90
          ? icon.PiBatteryFullFill
          : battery.percentage > 66
          ? icon.PiBatteryHighFill
          : battery.percentage > 33
          ? icon.PiBatteryMediumFill
          : battery.percentage > 5
          ? icon.PiBatteryLowFill
          : icon.PiBatteryWarning
        ),
        "  ",
        string(battery.percentage),
        "%"
      )
    onClick: open -> "ms-settings:powersleep"

  - type: settings
    template: icon.LuSettings2
    tooltip: '"Quick Settings"'
