name: Upload store MSIX to release

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *" # Run the action every 6 hours
  workflow_dispatch: # Manually run the action

jobs:
  upload-store-msix-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Upload store MSIX to release
        uses: JasonWei512/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release@v1
        with:
          store-id: 9p67c2d4t9fb
          token: ${{ secrets.GITHUB_TOKEN }}
